### ISSUE TITLE
Tile clickable area

### ISSUE THREAD

**Issue by raffaem** [AlynxZhou/showmethekey#18] opened 2023-02-07 09:59 UTC
I would like to tile the clickable area.

In this way I can put it below my terminal and it won't cover it, as the terminal window will be resized to fit in it.

But I cannot tile it.

I use Hyprland, and even if I dispatch "togglefloating" to it, it stays floating always.

**Comment by AlynxZhou** [comment] 2023-02-07 10:07
> I use Hyprland, and even if I dispatch "togglefloating" to it, it stays floating always.

I don't use Hyprland, so I can only guess the reason, maybe it requires window to be resizable to tile it? Unfortunately currently I set it to false, I have a testing branch that removes resizable as a side effect, but not released yet, I don't know if you are interested to build and try it: <https://github.com/AlynxZhou/showmethekey/tree/click-through-switch>.

**Comment by raffaem** [comment] 2023-02-07 10:13
> > I use Hyprland, and even if I dispatch "togglefloating" to it, it stays floating always.
> 
> I don't use Hyprland, so I can only guess the reason, maybe it requires window to be resizable to tile it? Unfortunately currently I set it to false, I have a testing branch that removes resizable as a side effect, but not released yet, I don't know if you are interested to build and try it: https://github.com/AlynxZhou/showmethekey/tree/click-through-switch.

Yep that tiles it. Thanks! :)

**Comment by raffaem** [comment] 2023-02-07 10:20
Even if I turn off the "Clickable" switch, the "Clickable" text is gone, but the keys still take up the same space as before, with taking up the empty space that was occupied by the "Clickable" text.

Is there a way to have the keys occupy all the available space?

**Comment by AlynxZhou** [comment] 2023-02-07 10:22
> Even if I turn off the "Clickable" switch, the "Clickable" text is gone, but the keys still take up the same space as before, with taking up the empty space that was occupied by the "Clickable" text.
> 
> Is there a way to have the keys occupy all the available space?

I am sorry, no solution, it's the title bar, window must have a title bar (so you could drag it). See this comment <https://github.com/AlynxZhou/showmethekey/issues/17#issuecomment-1420195173>.

**Comment by AlynxZhou** [comment] 2023-02-07 10:25
> > > I use Hyprland, and even if I dispatch "togglefloating" to it, it stays floating always.
> > 
> > 
> > I don't use Hyprland, so I can only guess the reason, maybe it requires window to be resizable to tile it? Unfortunately currently I set it to false, I have a testing branch that removes resizable as a side effect, but not released yet, I don't know if you are interested to build and try it: https://github.com/AlynxZhou/showmethekey/tree/click-through-switch.
> 
> Yep that tiles it. Thanks! :)

It should be easy to allow this in master, but I am thinking about merging the branch into master, if you have time please read <https://github.com/AlynxZhou/showmethekey/issues/17#issuecomment-1420225789> and give some opinion (because you just used the branch), thanks.

**Comment by raffaem** [comment] 2023-02-07 10:30
> > Even if I turn off the "Clickable" switch, the "Clickable" text is gone, but the keys still take up the same space as before, with taking up the empty space that was occupied by the "Clickable" text.
> > Is there a way to have the keys occupy all the available space?
> 
> I am sorry, no solution, it's the title bar, window must have a title bar (so you could drag it). See [#17 (comment)](https://github.com/AlynxZhou/showmethekey/issues/17#issuecomment-1420195173).

Thank you.

I don't understand this point.

For instance, as an image viewer I use feh, which does not seem to have a title bar? Also mpv does not seem to have one? Also kitty does not have one?

I think I render all of those without window decorations.

I can drag them / move them (not sure if they are exactly the same) with [mouse bindings](https://wiki.hyprland.org/Configuring/Binds/#mouse-binds)

**Comment by AlynxZhou** [comment] 2023-02-07 10:39
> > > Even if I turn off the "Clickable" switch, the "Clickable" text is gone, but the keys still take up the same space as before, with taking up the empty space that was occupied by the "Clickable" text.
> > > Is there a way to have the keys occupy all the available space?
> > 
> > 
> > I am sorry, no solution, it's the title bar, window must have a title bar (so you could drag it). See [#17 (comment)](https://github.com/AlynxZhou/showmethekey/issues/17#issuecomment-1420195173).
> 
> Thank you.
> 
> I don't understand this point.
> 
> For instance, as an image viewer I use feh, which does not seem to have a title bar? Also mpv does not seem to have one? Also kitty does not have one?
> 
> I think I render all of those without window decorations.
> 
> I can drag them / move them (not sure if they are exactly the same) with [mouse bindings](https://wiki.hyprland.org/Configuring/Binds/#mouse-binds)

It may be OK to remove titlebar from a GtkWindow, but not all people use Hyprland and get used to move window with a key pressed, for most people dragging window with titlebar is naturally, so I decide to keep it.

**Comment by raffaem** [comment] 2023-02-07 10:45
> It may be OK to remove titlebar from a GtkWindow, but not all people use Hyprland and get used to move window with a key pressed, for most people dragging window with titlebar is naturally, so I decide to keep it.

I think it's a feature of all tiling window managers, not only Hyprland (i3, sway, bspwm, etc.).

Maybe we can have a command line switch that remove windows decoration. So who uses a floating window manager can have the decorations.

**Comment by AlynxZhou** [comment] 2023-02-07 11:45
> > It may be OK to remove titlebar from a GtkWindow, but not all people use Hyprland and get used to move window with a key pressed, for most people dragging window with titlebar is naturally, so I decide to keep it.
> 
> I think it's a feature of all tiling window managers, not only Hyprland (i3, sway, bspwm, etc.).

The problem is most users are using floating window manager.

> Maybe we can have a command line switch that remove windows decoration. So who uses a floating window manager can have the decorations.

It could, but I don't want to take time on this, the title bar is little and should not waste too much screen space. Maybe I could make it smaller, but I have little interests on removing it.

**Comment by raffaem** [comment] 2023-02-09 06:07
> > > It may be OK to remove titlebar from a GtkWindow, but not all people use Hyprland and get used to move window with a key pressed, for most people dragging window with titlebar is naturally, so I decide to keep it.
> > 
> > 
> > I think it's a feature of all tiling window managers, not only Hyprland (i3, sway, bspwm, etc.).
> 
> The problem is most users are using floating window manager.
> 
> > Maybe we can have a command line switch that remove windows decoration. So who uses a floating window manager can have the decorations.
> 
> It could, but I don't want to take time on this, the title bar is little and should not waste too much screen space. Maybe I could make it smaller, but I have little interests on removing it.

Would you consider a PR that creates a new switch "Show Title Bar" in the main window?

**Comment by AlynxZhou** [comment] 2023-02-09 06:52
> > > > It may be OK to remove titlebar from a GtkWindow, but not all people use Hyprland and get used to move window with a key pressed, for most people dragging window with titlebar is naturally, so I decide to keep it.
> > > 
> > > 
> > > I think it's a feature of all tiling window managers, not only Hyprland (i3, sway, bspwm, etc.).
> > 
> > 
> > The problem is most users are using floating window manager.
> > > Maybe we can have a command line switch that remove windows decoration. So who uses a floating window manager can have the decorations.
> > 
> > 
> > It could, but I don't want to take time on this, the title bar is little and should not waste too much screen space. Maybe I could make it smaller, but I have little interests on removing it.
> 
> Would you consider a PR that creates a new switch "Show Title Bar" in the main window?

I personally don't consider it, because many people don't use it. The initial design is a floating window, it happens to be able to tile now, but not the main goal. Sorry.

**Comment by AlynxZhou** [comment] 2023-08-30 07:47
The window is resizable so user should be able to tile it, and I won't consider to remove window decorations (because I am a floating WM user), so I'll close this.

**Closed by AlynxZhou** 2023-08-30 07:47 UTC
